var DATA = {
  state: 0,
  message: '查询成功',
  total: 4214,
  pageNum: 71,
  pageNo: 1,
  pageSize: 60,
  Tflag: 0,
  result: [
    {
      name: '3D',
      code: '2025069',
      detailsLink: '/c/2025/03/20/609513.shtml',
      videoLink: '',
      date: '2025-03-20(四)',
      week: '四',
      red: '9,0,6',
      blue: '',
      blue2: '',
      sales: '131191350',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025068',
      detailsLink: '/c/2025/03/19/609406.shtml',
      videoLink: '',
      date: '2025-03-19(三)',
      week: '三',
      red: '5,5,5',
      blue: '',
      blue2: '',
      sales: '152420794',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025067',
      detailsLink: '/c/2025/03/18/609199.shtml',
      videoLink: '',
      date: '2025-03-18(二)',
      week: '二',
      red: '3,8,5',
      blue: '',
      blue2: '',
      sales: '152673322',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025066',
      detailsLink: '/c/2025/03/17/608892.shtml',
      videoLink: '',
      date: '2025-03-17(一)',
      week: '一',
      red: '7,2,0',
      blue: '',
      blue2: '',
      sales: '148542580',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025065',
      detailsLink: '/c/2025/03/16/608685.shtml',
      videoLink: '',
      date: '2025-03-16(日)',
      week: '日',
      red: '5,3,8',
      blue: '',
      blue2: '',
      sales: '141132818',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025064',
      detailsLink: '/c/2025/03/15/608679.shtml',
      videoLink: '/c/2025/03/15/608680.shtml',
      date: '2025-03-15(六)',
      week: '六',
      red: '9,2,8',
      blue: '',
      blue2: '',
      sales: '134319644',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025063',
      detailsLink: '/c/2025/03/14/608673.shtml',
      videoLink: '',
      date: '2025-03-14(五)',
      week: '五',
      red: '4,0,5',
      blue: '',
      blue2: '',
      sales: '140419336',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025062',
      detailsLink: '/c/2025/03/13/608366.shtml',
      videoLink: '',
      date: '2025-03-13(四)',
      week: '四',
      red: '8,1,0',
      blue: '',
      blue2: '',
      sales: '137961302',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025061',
      detailsLink: '/c/2025/03/12/608259.shtml',
      videoLink: '',
      date: '2025-03-12(三)',
      week: '三',
      red: '4,7,6',
      blue: '',
      blue2: '',
      sales: '139972702',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025060',
      detailsLink: '/c/2025/03/11/608052.shtml',
      videoLink: '',
      date: '2025-03-11(二)',
      week: '二',
      red: '9,3,8',
      blue: '',
      blue2: '',
      sales: '135621788',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025059',
      detailsLink: '/c/2025/03/10/607945.shtml',
      videoLink: '',
      date: '2025-03-10(一)',
      week: '一',
      red: '8,4,7',
      blue: '',
      blue2: '',
      sales: '136348478',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025058',
      detailsLink: '/c/2025/03/09/607837.shtml',
      videoLink: '',
      date: '2025-03-09(日)',
      week: '日',
      red: '4,0,5',
      blue: '',
      blue2: '',
      sales: '133680338',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025057',
      detailsLink: '/c/2025/03/08/607832.shtml',
      videoLink: '/c/2025/03/08/607833.shtml',
      date: '2025-03-08(六)',
      week: '六',
      red: '3,9,7',
      blue: '',
      blue2: '',
      sales: '132496790',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025056',
      detailsLink: '/c/2025/03/07/607826.shtml',
      videoLink: '',
      date: '2025-03-07(五)',
      week: '五',
      red: '4,9,2',
      blue: '',
      blue2: '',
      sales: '133846308',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025055',
      detailsLink: '/c/2025/03/06/607719.shtml',
      videoLink: '',
      date: '2025-03-06(四)',
      week: '四',
      red: '3,6,8',
      blue: '',
      blue2: '',
      sales: '129484966',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025054',
      detailsLink: '/c/2025/03/05/607612.shtml',
      videoLink: '',
      date: '2025-03-05(三)',
      week: '三',
      red: '4,9,7',
      blue: '',
      blue2: '',
      sales: '125276134',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025053',
      detailsLink: '/c/2025/03/04/607505.shtml',
      videoLink: '',
      date: '2025-03-04(二)',
      week: '二',
      red: '8,9,5',
      blue: '',
      blue2: '',
      sales: '125041488',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025052',
      detailsLink: '/c/2025/03/03/607398.shtml',
      videoLink: '',
      date: '2025-03-03(一)',
      week: '一',
      red: '5,8,5',
      blue: '',
      blue2: '',
      sales: '127550000',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025051',
      detailsLink: '/c/2025/03/02/607191.shtml',
      videoLink: '',
      date: '2025-03-02(日)',
      week: '日',
      red: '9,0,5',
      blue: '',
      blue2: '',
      sales: '127297032',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025050',
      detailsLink: '/c/2025/03/01/607185.shtml',
      videoLink: '/c/2025/03/01/607186.shtml',
      date: '2025-03-01(六)',
      week: '六',
      red: '8,0,6',
      blue: '',
      blue2: '',
      sales: '123449064',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025049',
      detailsLink: '/c/2025/02/28/607177.shtml',
      videoLink: '',
      date: '2025-02-28(五)',
      week: '五',
      red: '0,0,4',
      blue: '',
      blue2: '',
      sales: '128286352',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025048',
      detailsLink: '/c/2025/02/27/606970.shtml',
      videoLink: '',
      date: '2025-02-27(四)',
      week: '四',
      red: '6,4,0',
      blue: '',
      blue2: '',
      sales: '123604186',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025047',
      detailsLink: '/c/2025/02/26/606863.shtml',
      videoLink: '',
      date: '2025-02-26(三)',
      week: '三',
      red: '2,4,8',
      blue: '',
      blue2: '',
      sales: '123821540',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025046',
      detailsLink: '/c/2025/02/25/606656.shtml',
      videoLink: '',
      date: '2025-02-25(二)',
      week: '二',
      red: '4,9,0',
      blue: '',
      blue2: '',
      sales: '118687816',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025045',
      detailsLink: '/c/2025/02/24/606449.shtml',
      videoLink: '',
      date: '2025-02-24(一)',
      week: '一',
      red: '5,5,4',
      blue: '',
      blue2: '',
      sales: '121624432',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025044',
      detailsLink: '/c/2025/02/23/606242.shtml',
      videoLink: '',
      date: '2025-02-23(日)',
      week: '日',
      red: '9,1,2',
      blue: '',
      blue2: '',
      sales: '113960950',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025043',
      detailsLink: '/c/2025/02/22/606236.shtml',
      videoLink: '/c/2025/02/22/606237.shtml',
      date: '2025-02-22(六)',
      week: '六',
      red: '4,7,5',
      blue: '',
      blue2: '',
      sales: '115986908',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025042',
      detailsLink: '/c/2025/02/21/606230.shtml',
      videoLink: '',
      date: '2025-02-21(五)',
      week: '五',
      red: '7,7,5',
      blue: '',
      blue2: '',
      sales: '123557262',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025041',
      detailsLink: '/c/2025/02/20/606023.shtml',
      videoLink: '',
      date: '2025-02-20(四)',
      week: '四',
      red: '4,0,1',
      blue: '',
      blue2: '',
      sales: '123691424',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025040',
      detailsLink: '/c/2025/02/19/606016.shtml',
      videoLink: '',
      date: '2025-02-19(三)',
      week: '三',
      red: '4,2,8',
      blue: '',
      blue2: '',
      sales: '122303390',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025039',
      detailsLink: '/c/2025/02/18/605809.shtml',
      videoLink: '',
      date: '2025-02-18(二)',
      week: '二',
      red: '9,3,2',
      blue: '',
      blue2: '',
      sales: '119959874',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025038',
      detailsLink: '/c/2025/02/17/605602.shtml',
      videoLink: '',
      date: '2025-02-17(一)',
      week: '一',
      red: '8,4,7',
      blue: '',
      blue2: '',
      sales: '117073524',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025037',
      detailsLink: '/c/2025/02/16/605395.shtml',
      videoLink: '',
      date: '2025-02-16(日)',
      week: '日',
      red: '1,3,1',
      blue: '',
      blue2: '',
      sales: '118973646',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025036',
      detailsLink: '/c/2025/02/15/605389.shtml',
      videoLink: '/c/2025/02/15/605390.shtml',
      date: '2025-02-15(六)',
      week: '六',
      red: '6,1,7',
      blue: '',
      blue2: '',
      sales: '113719360',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025035',
      detailsLink: '/c/2025/02/14/605383.shtml',
      videoLink: '',
      date: '2025-02-14(五)',
      week: '五',
      red: '7,7,8',
      blue: '',
      blue2: '',
      sales: '122926880',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025034',
      detailsLink: '/c/2025/02/13/605176.shtml',
      videoLink: '',
      date: '2025-02-13(四)',
      week: '四',
      red: '2,6,1',
      blue: '',
      blue2: '',
      sales: '115398540',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025033',
      detailsLink: '/c/2025/02/12/605069.shtml',
      videoLink: '',
      date: '2025-02-12(三)',
      week: '三',
      red: '6,0,6',
      blue: '',
      blue2: '',
      sales: '112915394',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025032',
      detailsLink: '/c/2025/02/11/604862.shtml',
      videoLink: '',
      date: '2025-02-11(二)',
      week: '二',
      red: '4,9,9',
      blue: '',
      blue2: '',
      sales: '112635166',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025031',
      detailsLink: '/c/2025/02/10/604755.shtml',
      videoLink: '',
      date: '2025-02-10(一)',
      week: '一',
      red: '3,7,9',
      blue: '',
      blue2: '',
      sales: '110862208',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025030',
      detailsLink: '/c/2025/02/09/604548.shtml',
      videoLink: '',
      date: '2025-02-09(日)',
      week: '日',
      red: '3,0,2',
      blue: '',
      blue2: '',
      sales: '111521330',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025029',
      detailsLink: '/c/2025/02/08/604542.shtml',
      videoLink: '/c/2025/02/08/604543.shtml',
      date: '2025-02-08(六)',
      week: '六',
      red: '0,9,6',
      blue: '',
      blue2: '',
      sales: '108213326',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025028',
      detailsLink: '/c/2025/02/07/604336.shtml',
      videoLink: '',
      date: '2025-02-07(五)',
      week: '五',
      red: '4,0,9',
      blue: '',
      blue2: '',
      sales: '105047830',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025027',
      detailsLink: '/c/2025/02/06/604229.shtml',
      videoLink: '',
      date: '2025-02-06(四)',
      week: '四',
      red: '3,8,3',
      blue: '',
      blue2: '',
      sales: '112446958',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025026',
      detailsLink: '/c/2025/01/26/604022.shtml',
      videoLink: '',
      date: '2025-01-26(日)',
      week: '日',
      red: '5,8,8',
      blue: '',
      blue2: '',
      sales: '144082894',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025025',
      detailsLink: '/c/2025/01/25/603916.shtml',
      videoLink: '/c/2025/01/25/603917.shtml',
      date: '2025-01-25(六)',
      week: '六',
      red: '4,8,6',
      blue: '',
      blue2: '',
      sales: '138271464',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025024',
      detailsLink: '/c/2025/01/24/603910.shtml',
      videoLink: '',
      date: '2025-01-24(五)',
      week: '五',
      red: '7,6,2',
      blue: '',
      blue2: '',
      sales: '137606936',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025023',
      detailsLink: '/c/2025/01/23/603703.shtml',
      videoLink: '',
      date: '2025-01-23(四)',
      week: '四',
      red: '5,9,1',
      blue: '',
      blue2: '',
      sales: '130805322',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025022',
      detailsLink: '/c/2025/01/22/603596.shtml',
      videoLink: '',
      date: '2025-01-22(三)',
      week: '三',
      red: '6,3,8',
      blue: '',
      blue2: '',
      sales: '130150770',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025021',
      detailsLink: '/c/2025/01/21/603389.shtml',
      videoLink: '',
      date: '2025-01-21(二)',
      week: '二',
      red: '4,6,8',
      blue: '',
      blue2: '',
      sales: '128760978',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025020',
      detailsLink: '/c/2025/01/20/603082.shtml',
      videoLink: '',
      date: '2025-01-20(一)',
      week: '一',
      red: '0,5,6',
      blue: '',
      blue2: '',
      sales: '130478370',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025019',
      detailsLink: '/c/2025/01/19/602875.shtml',
      videoLink: '',
      date: '2025-01-19(日)',
      week: '日',
      red: '7,1,0',
      blue: '',
      blue2: '',
      sales: '131626900',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025018',
      detailsLink: '/c/2025/01/18/602869.shtml',
      videoLink: '/c/2025/01/18/602870.shtml',
      date: '2025-01-18(六)',
      week: '六',
      red: '8,3,6',
      blue: '',
      blue2: '',
      sales: '126827786',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025017',
      detailsLink: '/c/2025/01/17/602863.shtml',
      videoLink: '',
      date: '2025-01-17(五)',
      week: '五',
      red: '0,2,7',
      blue: '',
      blue2: '',
      sales: '129717920',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025016',
      detailsLink: '/c/2025/01/16/602656.shtml',
      videoLink: '',
      date: '2025-01-16(四)',
      week: '四',
      red: '1,0,4',
      blue: '',
      blue2: '',
      sales: '130737112',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025015',
      detailsLink: '/c/2025/01/15/602546.shtml',
      videoLink: '',
      date: '2025-01-15(三)',
      week: '三',
      red: '9,4,2',
      blue: '',
      blue2: '',
      sales: '125997960',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025014',
      detailsLink: '/c/2025/01/14/602339.shtml',
      videoLink: '',
      date: '2025-01-14(二)',
      week: '二',
      red: '6,7,9',
      blue: '',
      blue2: '',
      sales: '125072604',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025013',
      detailsLink: '/c/2025/01/13/602232.shtml',
      videoLink: '',
      date: '2025-01-13(一)',
      week: '一',
      red: '6,0,6',
      blue: '',
      blue2: '',
      sales: '128749584',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025012',
      detailsLink: '/c/2025/01/12/602025.shtml',
      videoLink: '',
      date: '2025-01-12(日)',
      week: '日',
      red: '4,8,7',
      blue: '',
      blue2: '',
      sales: '123431258',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025011',
      detailsLink: '/c/2025/01/11/602019.shtml',
      videoLink: '/c/2025/01/11/602020.shtml',
      date: '2025-01-11(六)',
      week: '六',
      red: '5,1,8',
      blue: '',
      blue2: '',
      sales: '115053974',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025010',
      detailsLink: '/c/2025/01/10/602013.shtml',
      videoLink: '',
      date: '2025-01-10(五)',
      week: '五',
      red: '3,3,3',
      blue: '',
      blue2: '',
      sales: '127921102',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025009',
      detailsLink: '/c/2025/01/09/601806.shtml',
      videoLink: '',
      date: '2025-01-09(四)',
      week: '四',
      red: '4,1,6',
      blue: '',
      blue2: '',
      sales: '122437942',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025008',
      detailsLink: '/c/2025/01/08/601599.shtml',
      videoLink: '',
      date: '2025-01-08(三)',
      week: '三',
      red: '2,6,0',
      blue: '',
      blue2: '',
      sales: '122295290',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025007',
      detailsLink: '/c/2025/01/07/601392.shtml',
      videoLink: '',
      date: '2025-01-07(二)',
      week: '二',
      red: '1,4,1',
      blue: '',
      blue2: '',
      sales: '122480048',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025006',
      detailsLink: '/c/2025/01/06/601285.shtml',
      videoLink: '',
      date: '2025-01-06(一)',
      week: '一',
      red: '8,9,8',
      blue: '',
      blue2: '',
      sales: '130352312',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025005',
      detailsLink: '/c/2025/01/05/601078.shtml',
      videoLink: '',
      date: '2025-01-05(日)',
      week: '日',
      red: '0,8,5',
      blue: '',
      blue2: '',
      sales: '127824192',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025004',
      detailsLink: '/c/2025/01/04/601072.shtml',
      videoLink: '/c/2025/01/04/601073.shtml',
      date: '2025-01-04(六)',
      week: '六',
      red: '6,3,4',
      blue: '',
      blue2: '',
      sales: '127119438',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025003',
      detailsLink: '/c/2025/01/03/601066.shtml',
      videoLink: '',
      date: '2025-01-03(五)',
      week: '五',
      red: '2,1,4',
      blue: '',
      blue2: '',
      sales: '132053224',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025002',
      detailsLink: '/c/2025/01/02/600958.shtml',
      videoLink: '',
      date: '2025-01-02(四)',
      week: '四',
      red: '9,1,6',
      blue: '',
      blue2: '',
      sales: '125620144',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
    {
      name: '3D',
      code: '2025001',
      detailsLink: '/c/2025/01/01/600852.shtml',
      videoLink: '',
      date: '2025-01-01(三)',
      week: '三',
      red: '7,0,3',
      blue: '',
      blue2: '',
      sales: '121010930',
      poolmoney: '',
      content: '',
      addmoney: '',
      addmoney2: '',
      msg: '',
      z2add: '',
      m2add: '',
      prizegrades: [
        {
          type: 1,
          typenum: '',
          typemoney: '',
        },
        {
          type: 2,
          typenum: '',
          typemoney: '',
        },
        {
          type: 3,
          typenum: '',
          typemoney: '',
        },
        {
          type: 4,
          typenum: '',
          typemoney: '',
        },
        {
          type: 5,
          typenum: '',
          typemoney: '',
        },
        {
          type: 6,
          typenum: '',
          typemoney: '',
        },
        {
          type: 7,
          typenum: '',
          typemoney: '',
        },
      ],
    },
  ],
}
